apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ include "ohdsi.atlas.name" . }}
  name: {{ include "ohdsi.atlas.name" . }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ include "ohdsi.atlas.name" . }}
  ports:
  - name: http
    port: {{ .Values.atlas.service.port }} 
    targetPort: {{ .Values.atlas.port }}