apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "ohdsi.webapi.name" . }}
  name: {{ include "ohdsi.webapi.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ohdsi.webapi.name" . }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ include "ohdsi.webapi.name" . }}
    spec:
      {{ if .Values.ingress.tls.enabled }}
      initContainers:
        - image: {{ .Values.webapi.image }}
          imagePullPolicy: Always
          name: pem-to-keystore
          command: ['/bin/bash']
          args: ['-c', "openssl pkcs12 -export -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password && keytool -importkeystore -noprompt -srckeystore $keystore_pkcs12 -srcstoretype pkcs12 -destkeystore $keystore_jks -storepass $password -srcstorepass $password -srcalias 1 -destalias tomcat"]
          env:
          # input files
          - name: crtfile
            value: /mnt/certificate/tls.crt
          - name: keyfile
            value: /mnt/certificate/tls.key

          # export files
          - name: keystore_pkcs12
            value: /mnt/keystore/keystore.pkcs12
          
          - name: keystore_jks
            value: /mnt/keystore/keystore.jks

          # Password for the certificate
          - name: password
            value: Ref4ct0r

          volumeMounts:         
          - mountPath: /mnt/keystore
            name: keystore-volume
          
          - mountPath: /mnt/certificate
            name: certificate
      {{ end }}

      containers:
        - image: {{ .Values.webapi.image }}
          imagePullPolicy: Always
          name: webapi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
          env:
          - name: DATASOURCE_DRIVERCLASSNAME
            value: {{ include "ohdsi.datasource.type" . }}

          - name: DATASOURCE_OHDSI_SCHEMA
            value: {{ .Values.datasource.schema }}

          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "ohdsi.datasource.password.secret" . }}
                key: {{ .Values.datasource.password.key }}

          - name: DATASOURCE_URL
            value: {{ include "ohdsi.datasource.url" . }}

          - name: DATASOURCE_USERNAME
            value: {{ .Values.datasource.user }}

          - name: FLYWAY_BASELINEDESCRIPTION
            value: {{ .Values.flyway.baseline.description }}

          - name: FLYWAY_BASELINEONMIGRATE
            value: {{ .Values.flyway.baseline.onMigrate | quote }}

          - name: FLYWAY_DATASOURCE_DRIVERCLASSNAME
            value: {{ include "ohdsi.flyway.datasource.type" .}}

          - name: FLYWAY_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "ohdsi.flyway.datasource.password.secret" . }}
                key: {{ .Values.flyway.datasource.password.key }}

          - name: FLYWAY_DATASOURCE_URL
            value: {{ include "ohdsi.flyway.datasource.url" . }}

          - name: FLYWAY_DATASOURCE_USERNAME
            value: {{ .Values.flyway.datasource.user }}

          - name: FLYWAY_LOCATIONS
            value: {{ .Values.flyway.locations }}

          - name: FLYWAY_PLACEHOLDERS_OHDSISCHEMA
            value: {{ .Values.flyway.placeholder.ohdsi.schema }}

          - name: FLYWAY_SCHEMAS
            value: {{ .Values.flyway.schemas }}

          - name: FLYWAY_TABLE
            value: {{ .Values.flyway.table }}

          - name: SECURITY_CORS_ENABLED
            value: {{ .Values.webapi.security.cors.enabled | quote }}

          - name: SECURITY_ORIGIN
            value: {{ .Values.webapi.security.cors.origin | quote }}

          - name: SPRING_BATCH_REPOSITORY_TABLEPREFIX
            value: {{ .Values.webapi.spring.batch.repository.tablePrefix | quote }}

          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
            value: {{ .Values.webapi.spring.jpa.properties.hibernate.defaultSchema }}

          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            value: {{ .Values.webapi.spring.jpa.properties.hibernate.dialect }}

          - name: flyway_baselineVersionAsString
            value: {{ .Values.flyway.baseline.version | quote }}

          {{ if ne .Values.security.provider "" }}          
          - name: SECURITY_PROVIDER
            value: {{ .Values.security.provider }}
          {{ end}}

          {{ if .Values.security.oid.enabled }}          
          - name: SECURITY_OID_ENABLED
            value: {{ .Values.security.oid.enabled | quote }}
          {{ end}}

          {{ if ne .Values.security.oid.clientId "" }}          
          - name: SECURITY_OID_CLIENTID
            value: {{ .Values.security.oid.clientId }}
          {{ end}}

          {{ if .Values.security.oid.apiSecret.secretName }}          
          - name: SECURITY_OID_APISECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.security.oid.apiSecret.secretName }}
                key: {{ .Values.security.oid.apiSecret.key }}
          {{ end}}

          {{ if ne .Values.security.oid.url "" }}          
          - name: SECURITY_OID_URL
            value: {{ .Values.security.oid.url }}
          {{ end}}

          {{ if ne .Values.security.oid.redirectUrl "" }}          
          - name: SECURITY_OID_REDIRECTURL
            value: {{ .Values.security.oid.redirectUrl }}
          {{ end}}

          {{ if .Values.ingress.tls.enabled }}
          - name: SECURITY_SSL_ENABLED
            value: "true"
          {{ end }}

          {{ if ne (include "ohdsi.webapi.javaopts" .) "" }}
          - name: JAVA_OPTS
            value: {{ include "ohdsi.webapi.javaopts" . }}
          {{ end }}

          {{ if .Values.webapi.env }}          
          {{ toYaml .Values.webapi.env | nindent 10 }}
          {{ end }}
          resources:
          {{ if .Values.webapi.resources }}          
          {{ toYaml .Values.webapi.resources | nindent 10 }}
          {{ end }}
          
          ports:
          - name: {{ include "ohdsi.webapi.portName" . }}
            containerPort: {{ include "ohdsi.webapi.port" . }}

          volumeMounts:
          - mountPath: /tmp
            name: ohdsi-webapi-tmpfs0

          {{ if .Values.ingress.tls.enabled }}
          - mountPath: /mnt/keystore
            name: keystore-volume
            readOnly: true
          {{ end }}

          {{ if .Values.webapi.volumeMounts }}          
          {{ toYaml .Values.webapi.volumeMounts | nindent 10 }}
          {{ end }}
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: ohdsi-webapi-tmpfs0

      {{ if .Values.ingress.tls.enabled }}
      - name: keystore-volume
        emptyDir: {}
      - name: certificate
        secret:
          secretName: {{ .Values.ingress.tls.secretName }}
      {{ end }}
      
      {{ if .Values.webapi.volumes }}
      {{ toYaml .Values.webapi.volumes | nindent 6 }}
      {{ end }}