{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:  
  name: {{ .Release.Name }}
  annotations: 
  {{ if .Values.ingress.annotations }}          
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{ end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ include "ohdsi.atlas.name" . }}
                port:
                  number: {{ .Values.atlas.service.port }}
            path: /atlas

          - pathType: Prefix
            backend:
              service:
                name: {{ include "ohdsi.webapi.name" . }}
                port:
                  number: {{ .Values.webapi.service.port }}
            path: /WebAPI

          - pathType: Prefix
            backend:
              service:
                name: {{ include "ohdsi.hades.name" . }}
                port:
                  number: {{ .Values.hades.service.port }}
            path: /

  {{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{ end }}
{{ end }}