{{- if not .Values.webapi.db.isExternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.datasource.password.secret" . }}
type: Opaque
data:
  {{ .Values.datasource.password.key }}: {{ .Values.atlasdb.password | b64enc }}
{{- end -}}